name: build-test

on: [push, delete]
jobs:
  norm_and_build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: alexandregv/norminette-action@v3
      with:
        flags: '.'

    - name: make test
      run: make
  
