name: build-test

on: [push, delete]
jobs:
  nominette:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: alexandregv/norminette-action@v3
      with:
        flags: '.'
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: make test
        run: make
  
